title: ✨ Eman's Engineering Blog ✨
email: feman4768@gmail.com
description: >- 
  A space for my Computer Engineering journey & programming fundamentals. 🎀

# URL Settings
url: "https://EmanFtima26.github.io" 
baseurl: ""

# Aesthetic Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# This allows us to use custom colors
sass:
  style: :compressed
